import { T } from "./theme";

export type Drug = {
  name: string;
  class: string;
  cat: string;
  ind: [number, number];
  maint: [number, number] | null;
  unit: string;
  munit: string | null;
  max: number;
  pf: number;
  onset: string;
  duration: string;
  elimination: string;
  protein: number;
  moa: string;
  ci: string;
  caution: string;
  side: string;
  note: string;
};

export const DRUGS: Drug[] = [
  {name:"Propofol",class:"Induction",cat:"Induction",ind:[1.5,2.5],maint:[4,12],unit:"mg/kg",munit:"mg/kg/h",max:250,pf:1.3,onset:"30-60 sec",duration:"5-10 min",elimination:"Hepatic + extrahepatic",protein:98,moa:"GABA-A potentiation",ci:"Egg/soya allergy, PRIS risk",caution:"Reduce 30-50% in elderly, hypovolaemia",side:"Hypotension, apnoea, pain on injection, PRIS",note:"TIVA: 4-12 mg/kg/h. Anti-emetic at sub-anaesthetic doses. Do not use >48h in paediatric ICU."},
  {name:"Thiopentone",class:"Induction",cat:"Induction",ind:[3,7],maint:null,unit:"mg/kg",munit:null,max:500,pf:1.2,onset:"15-30 sec",duration:"5-10 min",elimination:"Hepatic (CYP2C19)",protein:85,moa:"GABA-A potentiation (barbiturate)",ci:"Porphyria, airway obstruction, severe hypovolaemia",caution:"Reduce in elderly, renal/hepatic failure",side:"CVS depression, bronchospasm, histamine, tissue necrosis if extravascular",note:"Neuroprotection in raised ICP. Reconstitute to 2.5% solution."},
  {name:"Ketamine",class:"Induction",cat:"Induction",ind:[1,2],maint:[0.1,0.5],unit:"mg/kg",munit:"mg/kg/h",max:500,pf:1.0,onset:"30-60 sec IV / 3-5 min IM",duration:"10-20 min",elimination:"Hepatic (CYP3A4/2B6)",protein:12,moa:"NMDA receptor antagonist",ci:"Uncontrolled hypertension, psychosis, raised ICP (relative)",caution:"Use with BDZ to reduce emergence phenomena",side:"Emergence reactions, hypertension, tachycardia, hypersalivation",note:"IM dose: 4-8 mg/kg. Maintains airway reflexes. Bronchodilator. Sub-anaesthetic analgesia: 0.1-0.3 mg/kg IV."},
  {name:"Etomidate",class:"Induction",cat:"Induction",ind:[0.2,0.3],maint:null,unit:"mg/kg",munit:null,max:25,pf:1.0,onset:"15-45 sec",duration:"3-5 min",elimination:"Hepatic + plasma esterases",protein:75,moa:"GABA-A potentiation (imidazole)",ci:"Adrenal insufficiency, prolonged use",caution:"Single bolus only - adrenal suppression 4-8h",side:"Pain on injection, myoclonus, adrenal suppression, PONV",note:"Drug of choice in haemodynamic instability. Least cardiac depression."},
  {name:"Midazolam",class:"Sedation",cat:"Sedation",ind:[0.03,0.1],maint:[0.03,0.1],unit:"mg/kg",munit:"mg/kg/h",max:10,pf:1.0,onset:"2-3 min IV",duration:"15-80 min",elimination:"Hepatic (CYP3A4)",protein:96,moa:"GABA-A potentiation (benzodiazepine)",ci:"Acute angle-closure glaucoma",caution:"Elderly (reduce 50%), COPD, hepatic failure",side:"Respiratory depression, anterograde amnesia, paradoxical agitation",note:"Intranasal: 0.3 mg/kg (pedi). Reverse with flumazenil."},
  {name:"Dexmedetomidine",class:"Sedation",cat:"Sedation",ind:[0.5,1],maint:[0.2,0.7],unit:"mcg/kg",munit:"mcg/kg/h",max:200,pf:1.0,onset:"5-10 min",duration:"60-120 min",elimination:"Hepatic (CYP2A6)",protein:94,moa:"alpha2-adrenoceptor agonist",ci:"Advanced heart block (without pacemaker)",caution:"Loading -> transient hypertension then bradycardia/hypotension",side:"Bradycardia, hypotension, dry mouth",note:"Co-operative sedation. No respiratory depression. Reduces opioid requirements. Adjunct for awake FOI."},
  {name:"Sevoflurane",class:"Volatile",cat:"Induction",ind:[2,4],maint:[1,2.5],unit:"% (MAC)",munit:"% (MAC)",max:8,pf:1.0,onset:"Rapid (blood:gas 0.65)",duration:"Rapid offset",elimination:"Pulmonary 96%, hepatic 5%",protein:0,moa:"Multi-channel (GABA, glycine, HCN)",ci:"MH susceptibility, halogenated agent hepatotoxicity",caution:"Compound A (renal) at low flows <1 L/min",side:"MH trigger, CVS depression, mild airway irritation",note:"MAC=2.0%. Smooth inhalation induction (pedi). Compound A nephrotoxicity theoretical."},
  {name:"Desflurane",class:"Volatile",cat:"Induction",ind:[3,6],maint:[3,9],unit:"% (MAC)",munit:"% (MAC)",max:18,pf:1.0,onset:"Very rapid (blood:gas 0.42)",duration:"Fastest recovery",elimination:"Pulmonary >99%",protein:0,moa:"Ion channel modulation",ci:"MH susceptibility",caution:"Airway irritant - avoid induction. Requires heated vaporiser.",side:"Airway irritation, sympathetic stimulation, MH",note:"MAC=6%. Ultra-fast emergence. Ideal for long/obese cases. Do NOT use for inhalational induction."},
  {name:"Nitrous Oxide",class:"Inhalational",cat:"Induction",ind:[50,70],maint:[50,70],unit:"% inhaled",munit:"% inhaled",max:70,pf:1.0,onset:"Rapid",duration:"Rapid offset",elimination:"Pulmonary",protein:0,moa:"NMDA antagonism + opioid receptor modulation",ci:"Pneumothorax, bowel obstruction, middle ear surgery, B12 deficiency, raised ICP",caution:"Diffusion hypoxia on discontinuation - give 100% O2",side:"PONV (high), bone marrow suppression (prolonged), megaloblastic anaemia",note:"MAC=104%. 30x more soluble than N2 - expands gas spaces. Inhibits methionine synthase."},
  {name:"Fentanyl",class:"Opioid",cat:"Opioids",ind:[1,3],maint:[1,2],unit:"mcg/kg",munit:"mcg/kg/h",max:500,pf:1.0,onset:"1-2 min",duration:"30-60 min",elimination:"Hepatic (CYP3A4)",protein:84,moa:"mu-opioid receptor agonist",ci:"MAO inhibitors",caution:"Respiratory depression, chest wall rigidity (large bolus)",side:"Pruritus, nausea, respiratory depression",note:"Most widely used intraoperative opioid. Neuraxial: 1-2 mcg/mL. Patch: 25-100 mcg/h."},
  {name:"Remifentanil",class:"Opioid",cat:"Opioids",ind:[0.5,1],maint:[0.05,0.4],unit:"mcg/kg",munit:"mcg/kg/min",max:200,pf:1.0,onset:"1 min",duration:"5-10 min (context-insensitive)",elimination:"Blood/tissue esterases",protein:70,moa:"mu-opioid agonist (ultra-short)",ci:"Epidural/intrathecal (glycine preservative)",caution:"NO residual analgesia - plan multimodal at cessation",side:"Bradycardia, hypotension, acute opioid tolerance",note:"Context-insensitive T1/2 ~3 min regardless of duration. Perfect for craniotomy, airway surgery. Always plan post-op analgesia."},
  {name:"Morphine",class:"Opioid",cat:"Opioids",ind:[0.1,0.2],maint:null,unit:"mg/kg",munit:null,max:20,pf:1.0,onset:"5-10 min",duration:"3-5 h",elimination:"Hepatic glucuronidation",protein:35,moa:"mu-opioid receptor agonist",ci:"Acute asthma, severe hepatic/renal failure",caution:"M6G accumulates in renal failure",side:"Histamine release, nausea, pruritus, urinary retention",note:"Gold standard analgesic. Intrathecal: 0.1-0.3 mg. Epidural: 2-4 mg. PCA: 1 mg bolus."},
  {name:"Sufentanil",class:"Opioid",cat:"Opioids",ind:[0.2,0.5],maint:[0.1,0.3],unit:"mcg/kg",munit:"mcg/kg/h",max:30,pf:0.9,onset:"1-3 min",duration:"30-60 min",elimination:"Hepatic + intestinal",protein:92.5,moa:"mu-opioid agonist (5-10x fentanyl)",ci:"MAO inhibitors",caution:"High potency - titrate carefully",side:"Chest wall rigidity, bradycardia, respiratory depression",note:"5-10x more potent than fentanyl. Excellent for cardiac surgery. Neuraxial: 5-10 mcg."},
  {name:"Alfentanil",class:"Opioid",cat:"Opioids",ind:[10,30],maint:[0.5,1],unit:"mcg/kg",munit:"mcg/kg/min",max:2000,pf:1.0,onset:"<1 min",duration:"10-20 min",elimination:"Hepatic (CYP3A4)",protein:92,moa:"mu-opioid receptor agonist",ci:"MAO inhibitors",caution:"Erythromycin/fluconazole increase levels",side:"Nausea, respiratory depression, bradycardia",note:"Rapid onset. Good for short painful stimuli. Laryngoscopy blunting: 10-20 mcg/kg."},
  {name:"Rocuronium",class:"NMBA",cat:"NMBA",ind:[0.6,1.2],maint:[0.1,0.2],unit:"mg/kg",munit:"mg/kg prn",max:200,pf:1.0,onset:"60-90 sec",duration:"30-60 min",elimination:"Biliary/hepatic",protein:30,moa:"Competitive nicotinic ACh receptor antagonist",ci:"Known hypersensitivity",caution:"Reduced in hepatic failure",side:"Anaphylaxis (highest NMBA risk), bronchospasm",note:"RSI: 1.2 mg/kg. Reverse: sugammadex 16 mg/kg (immediate). Dose-dependent duration."},
  {name:"Suxamethonium",class:"Depolarising NMBA",cat:"NMBA",ind:[1,1.5],maint:null,unit:"mg/kg",munit:null,max:200,pf:1.5,onset:"45-60 sec",duration:"8-12 min",elimination:"Plasma cholinesterase",protein:0,moa:"Depolarising nicotinic ACh receptor agonist",ci:"MH susceptibility, hyperkalaemia, denervation, burns >24h, muscular dystrophy",caution:"Pseudocholinesterase deficiency (prolonged block)",side:"Hyperkalaemia (+0.5-1 mEq/L), MH, bradycardia, myalgia, raised IOP/ICP",note:"RSI drug of choice for rapid offset. Pedi: 2 mg/kg. Phase 2 block if >3-5 mg/kg total."},
  {name:"Atracurium",class:"NMBA",cat:"NMBA",ind:[0.4,0.5],maint:[0.1,0.2],unit:"mg/kg",munit:"mg/kg prn",max:100,pf:1.0,onset:"2-3 min",duration:"20-35 min",elimination:"Hofmann + plasma esterases (organ-independent)",protein:82,moa:"Competitive nicotinic ACh receptor antagonist",ci:"Known hypersensitivity",caution:"Laudanosine accumulation theoretical in renal failure",side:"Histamine release, hypotension, flushing",note:"Drug of choice in multi-organ failure. Organ-independent elimination. Inject slowly (histamine)."},
  {name:"Cisatracurium",class:"NMBA",cat:"NMBA",ind:[0.1,0.15],maint:[0.03,0.06],unit:"mg/kg",munit:"mg/kg/h",max:20,pf:1.0,onset:"2-3 min",duration:"40-75 min",elimination:"Hofmann (predominantly)",protein:82,moa:"Competitive nicotinic ACh receptor antagonist",ci:"Known hypersensitivity",caution:"Slower onset than atracurium",side:"Minimal histamine release",note:"Preferred over atracurium in ICU (less laudanosine). Organ-independent."},
  {name:"Sugammadex",class:"Reversal",cat:"Reversal",ind:[2,16],maint:null,unit:"mg/kg",munit:null,max:500,pf:1.0,onset:"2-3 min",duration:"Permanent encapsulation",elimination:"Renal (unchanged)",protein:0,moa:"Modified gamma-cyclodextrin - encapsulates rocuronium/vecuronium",ci:"Known hypersensitivity",caution:"Hormonal contraceptives ineffective 7 days",side:"Anaphylaxis (0.3%), bradycardia, QT prolongation",note:"Routine reversal (T2): 2 mg/kg. Moderate block: 4 mg/kg. Immediate RSI reversal: 16 mg/kg."},
  {name:"Neostigmine",class:"Reversal",cat:"Reversal",ind:[0.04,0.07],maint:null,unit:"mg/kg",munit:null,max:5,pf:1.0,onset:"5-10 min",duration:"30-60 min",elimination:"Renal + hepatic",protein:15,moa:"Acetylcholinesterase inhibitor",ci:"GI/urinary obstruction",caution:"Always with anticholinergic. Only reverse shallow block (TOF >=2).",side:"Bradycardia, bronchospasm (without anticholinergic), salivation",note:"Pair with glycopyrrolate 0.01 mg/kg. TOF ratio >=0.9 before extubation."},
  {name:"Naloxone",class:"Reversal",cat:"Reversal",ind:[0.01,0.04],maint:[0.005,0.01],unit:"mg/kg",munit:"mg/kg/h",max:2,pf:1.0,onset:"1-2 min",duration:"30-90 min",elimination:"Hepatic",protein:50,moa:"Competitive mu/kappa/delta opioid receptor antagonist",ci:"Opioid dependence (withdrawal)",caution:"Shorter duration than opioids - re-dose or infuse. May precipitate pulmonary oedema.",side:"Acute pain, withdrawal, hypertension, tachycardia",note:"Give 0.04 mg increments IV (NOT 0.4 mg - acute pain). Infusion: 0.005 mg/kg/h."},
  {name:"Lidocaine",class:"Local Anaesthetic",cat:"Local Anaesthetic",ind:[3,7],maint:null,unit:"mg/kg",munit:null,max:500,pf:1.0,onset:"2-5 min",duration:"60-120 min",elimination:"Hepatic (CYP1A2/3A4)",protein:65,moa:"Voltage-gated Na+ channel blockade",ci:"High-degree heart block, severe hepatic failure",caution:"Max: 3 mg/kg plain, 7 mg/kg with adrenaline",side:"CNS: tingling, tinnitus, seizures. CVS: arrhythmia (LAST)",note:"IV infusion: 1-1.5 mg/kg bolus then 1.5 mg/kg/h (perioperative analgesia). Topical airway: 4-9 mg/kg."},
  {name:"Bupivacaine",class:"Local Anaesthetic",cat:"Local Anaesthetic",ind:[1.5,2.5],maint:null,unit:"mg/kg",munit:null,max:175,pf:1.0,onset:"15-30 min",duration:"240-480 min",elimination:"Hepatic",protein:95,moa:"Voltage-gated Na+ channel blockade",ci:"IV regional (Bier block - high CVS toxicity)",caution:"Max: 2 mg/kg plain, 2.5 mg/kg with adrenaline. Highly cardiotoxic.",side:"Severe CVS toxicity - difficult to treat",note:"Spinal: 0.5% heavy 2-3 mL. Epidural: 0.25-0.5%. Most widely used for regional."},
  {name:"Ropivacaine",class:"Local Anaesthetic",cat:"Local Anaesthetic",ind:[2,3],maint:null,unit:"mg/kg",munit:null,max:300,pf:1.0,onset:"10-20 min",duration:"180-360 min",elimination:"Hepatic",protein:94,moa:"Na+ channel blockade (S-enantiomer)",ci:"IV regional (relative)",caution:"Less cardiotoxic than bupivacaine",side:"Moderate LAST risk (less than bupivacaine)",note:"Preferred for peripheral blocks and epidurals. 0.2-0.375% analgesia, 0.5-0.75% surgery."},
  {name:"Norepinephrine",class:"Vasopressor",cat:"Vasopressors",ind:[0.05,0.5],maint:[0.01,2],unit:"mcg/kg/min",munit:"mcg/kg/min",max:200,pf:1.0,onset:"1-2 min",duration:"Infusion-dependent",elimination:"MAO + COMT",protein:0,moa:"alpha1>alpha2 + beta1 -> vasoconstriction + moderate inotropy",ci:"Hypovolaemia (uncorrected)",caution:"Extravasation -> necrosis (central line preferred)",side:"Reflex bradycardia, peripheral ischaemia",note:"1st-line vasopressor for septic/vasodilatory shock. Target MAP >=65 mmHg."},
  {name:"Epinephrine",class:"Vasopressor",cat:"Vasopressors",ind:[0.01,1],maint:[0.01,1],unit:"mcg/kg/min",munit:"mcg/kg/min",max:200,pf:1.0,onset:"Seconds",duration:"Infusion-dependent",elimination:"MAO + COMT",protein:0,moa:"alpha+beta1+beta2 - dose-dependent",ci:"Closed-angle glaucoma (relative)",caution:"Anaphylaxis: 0.01 mg/kg IV. Cardiac arrest: 1 mg bolus.",side:"Tachycardia, arrhythmia, lactic acidosis",note:"Anaphylaxis: 0.01 mg/kg IV or IM. Cardiac arrest: 1 mg q3-5 min."},
  {name:"Phenylephrine",class:"Vasopressor",cat:"Vasopressors",ind:[0.5,2],maint:[0.5,5],unit:"mcg/kg bolus",munit:"mcg/kg/min",max:200,pf:1.0,onset:"1-3 min",duration:"10-20 min",elimination:"MAO + hepatic",protein:0,moa:"Pure alpha1 agonist - no inotropy",ci:"Severe bradycardia, HF",caution:"Reflex bradycardia",side:"Reflex bradycardia, reduced CO",note:"Spinal/epidural hypotension: 50-200 mcg boluses. Safe in obstetrics."},
  {name:"Vasopressin",class:"Vasopressor",cat:"Vasopressors",ind:[0.01,0.04],maint:[0.01,0.04],unit:"U/min",munit:"U/min",max:0.1,pf:1.0,onset:"1-2 min",duration:"Infusion-dependent",elimination:"Hepatic + renal",protein:0,moa:"V1 receptor (vascular smooth muscle) + V2 (renal)",ci:"Mesenteric/coronary disease (high doses)",caution:"Fixed-dose non-catecholamine",side:"Mesenteric ischaemia, hyponatraemia",note:"Catecholamine-refractory shock. Fixed dose (not titrated). Add-on to norepinephrine."},
  {name:"Dobutamine",class:"Inotrope",cat:"Inotropes",ind:[2,20],maint:[2,20],unit:"mcg/kg/min",munit:"mcg/kg/min",max:40,pf:1.0,onset:"1-2 min",duration:"Infusion-dependent",elimination:"MAO + COMT",protein:0,moa:"beta1>beta2 agonism - positive inotropy + mild vasodilation",ci:"HOCM, tachyarrhythmia",caution:"May decreased BP; add vasopressor if hypotensive",side:"Tachycardia, arrhythmia, hypotension",note:"Cardiogenic shock, low CO states. Stress echo. Tolerance develops >72h."},
  {name:"Ondansetron",class:"Antiemetic",cat:"Antiemetic",ind:[0.05,0.1],maint:null,unit:"mg/kg",munit:null,max:8,pf:1.0,onset:"15-30 min",duration:"6-12 h",elimination:"Hepatic (CYP3A4)",protein:73,moa:"5-HT3 receptor antagonist",ci:"Prolonged QT, congenital long QT",caution:"QTc prolongation",side:"Headache, constipation, QT prolongation",note:"1st-line PONV. 4 mg standard adult dose. 8 mg high risk."},
  {name:"Dexamethasone",class:"Steroid/Antiemetic",cat:"Antiemetic",ind:[0.1,0.15],maint:null,unit:"mg/kg",munit:null,max:10,pf:1.0,onset:"2-4 h",duration:"36-72 h",elimination:"Hepatic",protein:77,moa:"Glucocorticoid",ci:"Active infection (relative), uncontrolled DM",caution:"Single dose safe. Hyperglycaemia.",side:"Hyperglycaemia, perineal burning (IV)",note:"PONV: 4-8 mg at induction. Analgesic-sparing. Anti-inflammatory. Give at induction."},
  {name:"Paracetamol",class:"Analgesic",cat:"Analgesic",ind:[10,15],maint:[10,15],unit:"mg/kg",munit:"mg/kg q4-6h",max:1000,pf:1.0,onset:"30-60 min IV",duration:"4-6 h",elimination:"Hepatic (glucuronidation/sulfation/CYP2E1)",protein:10,moa:"COX inhibition (central), serotonergic modulation",ci:"Severe hepatic impairment",caution:"Max 4g/day (3g if liver risk). Overdose -> hepatic failure.",side:"Hepatotoxicity (overdose)",note:"IV over 15 min. Reduces opioid need ~30%. Standard multimodal analgesia. NAC antidote."},
  {name:"Ketorolac",class:"NSAID",cat:"Analgesic",ind:[0.15,0.5],maint:null,unit:"mg/kg",munit:null,max:30,pf:1.0,onset:"15-30 min",duration:"4-6 h",elimination:"Renal",protein:99,moa:"Non-selective COX-1/2 inhibitor",ci:"Renal failure, GI ulcer, coagulopathy, last trimester",caution:"Limit 5 days. GI/renal/platelet risk.",side:"GI ulceration, renal impairment, platelet inhibition",note:"IV/IM NSAID with opioid-equivalent analgesia. 30 mg IV (young/healthy), 15 mg (elderly)."},
  {name:"Metamizol",class:"Non-opioid Analgesic",cat:"Analgesic",ind:[15,20],maint:[15,20],unit:"mg/kg",munit:"mg/kg q6h",max:1000,pf:1.0,onset:"30 min IV",duration:"4-6 h",elimination:"Hepatic + renal (metabolites)",protein:58,moa:"COX-1/2/3 inhibition + central + cannabinoid pathways",ci:"Pyrazolone allergy, G6PD deficiency, acute hepatic porphyria, agranulocytosis history, 3rd trimester pregnancy",caution:"Infuse slowly (>=15 min) - rapid IV -> hypotension/anaphylaxis. Monitor FBC on prolonged use (agranulocytosis ~1:1500).",side:"Agranulocytosis (rare but serious), hypotension, anaphylaxis, Stevens-Johnson",note:"Widely used in Germany (Novalgin/Novaminsulfon). 1g IV over 15 min q6h, max 4g/day. Strong analgesic + antipyretic + spasmolytic. Per DGAI: dilute in 100 mL NaCl, infuse slowly. Inform patient of agranulocytosis warning signs."},
  {name:"Gabapentin",class:"Analgesic",cat:"Analgesic",ind:[600,900],maint:null,unit:"mg oral (preop)",munit:null,max:900,pf:1.0,onset:"1-2 h oral",duration:"8-12 h",elimination:"Renal (unchanged)",protein:3,moa:"alpha2delta Ca2+ channel subunit blocker",ci:"Severe renal failure",caution:"Sedation + dizziness. Potentiates respiratory depression with opioids.",side:"Sedation, dizziness, ataxia",note:"Preoperative 600-900 mg PO. Reduces opioid use and acute pain scores. Neuropathic adjuvant."},
  {name:"Magnesium Sulphate",class:"Analgesic",cat:"Analgesic",ind:[30,50],maint:[8,15],unit:"mg/kg load",munit:"mg/kg/h",max:2000,pf:1.0,onset:"5-15 min",duration:"Infusion-dependent",elimination:"Renal",protein:0,moa:"NMDA receptor antagonism, Ca2+ channel modulation",ci:"Hypocalcaemia, AV block, renal failure",caution:"Monitor: patellar reflex loss (toxicity), resp. depression",side:"Flushing, hypotension, respiratory arrest (toxic)",note:"Opioid-sparing. Anti-hyperalgesic. Eclampsia: 4g load then 1g/h. Therapeutic: 2-4 mmol/L."},
  {name:"Tranexamic Acid",class:"Antifibrinolytic",cat:"Other",ind:[10,15],maint:[1,1],unit:"mg/kg load",munit:"mg/kg/h",max:1000,pf:1.0,onset:"Minutes",duration:"Infusion-dependent",elimination:"Renal (unchanged)",protein:3,moa:"Lysine analogue - blocks plasminogen binding to fibrin",ci:"Active thromboembolic disease",caution:"Give within 3h of trauma (CRASH-2). Seizures at very high doses.",side:"Nausea, diarrhoea, seizures (high/intrathecal doses)",note:"Major haemorrhage: 1g IV over 10 min then 1g over 8h. Trauma: within 3h. TXA rinse in haemophilia."},
  {name:"Atropine",class:"Emergency",cat:"Emergency",ind:[0.01,0.02],maint:null,unit:"mg/kg",munit:null,max:3,pf:1.0,onset:"1-2 min IV",duration:"30-60 min",elimination:"Hepatic + renal",protein:18,moa:"Competitive muscarinic antagonist",ci:"Tachyarrhythmia, closed-angle glaucoma",caution:"Min IV dose 0.1 mg (paradoxical bradycardia in children). Max 3 mg.",side:"Tachycardia, dry mouth, urinary retention, delirium (elderly)",note:"Sinus bradycardia: 0.5-1 mg IV. Peds: 0.02 mg/kg. Organophosphate: 2-4 mg repeated."},
  {name:"Dantrolene",class:"Emergency",cat:"Emergency",ind:[2.5,10],maint:[1,2],unit:"mg/kg IV bolus",munit:"mg/kg q6h x24h",max:30,pf:1.0,onset:"Minutes",duration:"Variable",elimination:"Hepatic (CYP3A4)",protein:0,moa:"Ryanodine receptor blocker - prevents SR Ca2+ release",ci:"None (life-threatening emergency)",caution:"Reconstitute each 20mg vial in 60mL warm water.",side:"Weakness, drowsiness, phlebitis",note:"MH ANTIDOTE. 2.5 mg/kg IV, repeat q5 min until ETCO2 normalises. Max 30 mg/kg."},
  {name:"Intralipid 20%",class:"Emergency",cat:"Emergency",ind:[1.5,1.5],maint:[0.25,0.25],unit:"mL/kg bolus",munit:"mL/kg/min",max:12,pf:1.0,onset:"Minutes",duration:"Infusion-dependent",elimination:"Lipid metabolism",protein:0,moa:"Lipid sink - sequesters LA. Metabolic cardiac rescue.",ci:"Egg/soya allergy (relative - emergency overrides)",caution:"Max 12 mL/kg in first 30 min.",side:"Lipid overload, pancreatitis (excess)",note:"LAST. 1.5 mL/kg bolus over 1 min then 0.25 mL/kg/min. Repeat bolus x2. Alert ECMO centre."},
  {name:"Amiodarone",class:"Antiarrhythmic",cat:"Antiarrhythmic",ind:[5,5],maint:[10,20],unit:"mg/kg load",munit:"mg/kg over 24h",max:1200,pf:1.0,onset:"Minutes-hours IV",duration:"Weeks (T1/2 40-55 days)",elimination:"Hepatic",protein:96,moa:"Class III (K+ block) + I + II + IV (multi-class)",ci:"Thyroid disease, severe bradycardia/AV block",caution:"Multiple interactions (warfarin, digoxin). Pulmonary toxicity (chronic).",side:"Phlebitis, bradycardia, pulmonary toxicity, thyroid dysfunction",note:"VF/pulseless VT: 300 mg bolus. Stable VT: 150 mg over 10 min. Do NOT mix in same line."},
  {name:"Adenosine",class:"Antiarrhythmic",cat:"Antiarrhythmic",ind:[0.1,0.3],maint:null,unit:"mg/kg",munit:null,max:18,pf:1.0,onset:"Seconds",duration:"10-30 sec",elimination:"Red blood cells (adenosine deaminase)",protein:0,moa:"A1 receptor -> AV node conduction block (transient)",ci:"Asthma, sick sinus syndrome, 2nd/3rd degree AV block",caution:"Rapid bolus with immediate flush essential",side:"Chest tightness, flushing, transient bradycardia, bronchospasm",note:"SVT termination. Adult: 6 mg -> 12 mg -> 18 mg rapid bolus. Antagonised by caffeine/theophylline."},
  {name:"Labetalol",class:"Antihypertensive",cat:"Antihypertensive",ind:[0.1,1],maint:[1,2],unit:"mg/kg",munit:"mg/kg/h",max:200,pf:1.0,onset:"2-5 min",duration:"6-18 h",elimination:"Hepatic",protein:50,moa:"alpha1 + beta1,beta2 antagonist",ci:"Reactive airways, decompensated HF, bradycardia",caution:"Avoid in cocaine toxicity (unopposed alpha), asthma",side:"Bradycardia, hypotension, bronchospasm",note:"Safe in pregnancy. Bolus: 5-20 mg IV increments. Infusion: 1-2 mg/min."},
  {name:"Esmolol",class:"Antihypertensive",cat:"Antihypertensive",ind:[0.5,1],maint:[0.05,0.3],unit:"mg/kg",munit:"mg/kg/min",max:500,pf:1.0,onset:"1-2 min",duration:"10-20 min",elimination:"Red blood cell esterases",protein:55,moa:"Ultra-short beta1-selective antagonist",ci:"Severe bradycardia, AV block, severe asthma",caution:"Avoid in reactive airways",side:"Bradycardia, hypotension",note:"Blunts intubation response: 1-1.5 mg/kg. Rate control in tachyarrhythmia. T1/2 ~9 min."},
  {name:"Hydrocortisone",class:"Steroid",cat:"Steroid",ind:[1.5,3],maint:[1.5,2],unit:"mg/kg",munit:"mg/kg q6h",max:200,pf:1.0,onset:"2-4 h",duration:"8-12 h",elimination:"Hepatic",protein:90,moa:"Glucocorticoid + mineralocorticoid",ci:"Active untreated infection",caution:"Hyperglycaemia; masks infection signs",side:"Hyperglycaemia, hypertension, immunosuppression",note:"Anaphylaxis: 200 mg IV (adjunct only). Adrenal crisis: 100 mg IV then 200 mg/24h."},
  {name:"Salbutamol",class:"Bronchodilator",cat:"Bronchodilator",ind:[2.5,5],maint:null,unit:"mg nebulised",munit:null,max:10,pf:1.0,onset:"5-15 min",duration:"4-6 h",elimination:"Lung + hepatic",protein:0,moa:"beta2-adrenoceptor agonist -> bronchodilation",ci:"None absolute",caution:"Tachycardia, hypokalaemia (high doses)",side:"Tachycardia, tremor, hypokalaemia",note:"Intraoperative bronchospasm: 4-8 MDI puffs via catheter mount. IV: 5-10 mcg/min. HyperK: 10 mg nebulised."},
];

export type Nerve = {
  id: string; name: string; region: string; icon: string;
  depth: string; vol: string; agent: string; landmark: string;
  us: string; indication: string; risk: string; mechanism: string; extra?: string;
};

export const NERVES: Nerve[] = [
  {id:"isbp",name:"Interscalene",region:"Shoulder / C5-C6",icon:"🫁",depth:"1-3 cm",vol:"15-20 mL",agent:"Ropivacaine 0.5%",landmark:"Post to SCM at C6 (Chassaignac tubercle)",us:"Nerve roots between anterior/middle scalene ('traffic lights')",indication:"Shoulder surgery, proximal humerus, AC joint",risk:"Phrenic nerve (100%) - avoid bilateral or poor lung function. Horner, pneumothorax <1%.",mechanism:"Blocks upper/middle trunk C5-C6 (+/-C7)",extra:"Bilateral ISBPs contraindicated. 'Spinal of the shoulder'."},
  {id:"supra",name:"Supraclavicular",region:"Arm / C5-T1",icon:"💪",depth:"1-4 cm",vol:"20-30 mL",agent:"Ropivacaine 0.375-0.5%",landmark:"Lateral to SCM, above clavicle",us:"Brachial plexus lateral to subclavian artery ('cluster of grapes')",indication:"Elbow, forearm, hand surgery",risk:"Phrenic nerve 50%, pneumothorax <1%, Horner syndrome",mechanism:"Blocks all trunks/divisions - reliable for distal arm",extra:"Best single-injection block for upper extremity. 'Spinal of the arm'."},
  {id:"infra",name:"Infraclavicular",region:"Forearm / Hand",icon:"🤝",depth:"3-6 cm",vol:"25-35 mL",agent:"Ropivacaine 0.375%",landmark:"2 cm medial to coracoid process",us:"Three cords around axillary artery (6, 9, 12 o'clock)",indication:"Forearm and hand surgery, PICC placement",risk:"Vascular puncture, pneumothorax (rare)",mechanism:"Blocks lateral, medial, posterior cords",extra:"Good for catheter placement. Less movement than axillary."},
  {id:"axil",name:"Axillary",region:"Hand / Wrist",icon:"✋",depth:"1-3 cm",vol:"30-40 mL",agent:"Lidocaine 1.5% + ropivacaine 0.375%",landmark:"Axillary artery pulsation in axilla",us:"4 terminal nerves around axillary artery",indication:"Hand and wrist surgery",risk:"Intravascular injection (most common), nerve injury",mechanism:"Blocks median, ulnar, radial + musculocutaneous",extra:"Musculocutaneous often separate - inject into coracobrachialis."},
  {id:"femoral",name:"Femoral",region:"Anterior thigh / Knee",icon:"🦵",depth:"2-4 cm",vol:"20-30 mL",agent:"Ropivacaine 0.375%",landmark:"1 cm lateral to femoral artery",us:"Femoral nerve lateral to artery, below fascia iliaca",indication:"TKA, femur fractures, hip surgery",risk:"Quadriceps weakness (fall risk), vascular puncture",mechanism:"Blocks anterior femoral cutaneous + saphenous + motor to quads",extra:"Consider adductor canal block for TKA - preserves quad strength."},
  {id:"adductor",name:"Adductor Canal",region:"Medial thigh / Knee",icon:"🦴",depth:"3-5 cm",vol:"15-20 mL",agent:"Ropivacaine 0.25%",landmark:"Medial thigh, mid-thigh level",us:"Saphenous nerve with femoral artery under sartorius",indication:"TKA, knee arthroscopy, ankle surgery (medial)",risk:"Femoral artery puncture, haematoma",mechanism:"Primarily sensory - spares quadriceps (mobility-preserving)",extra:"Preferred to femoral nerve block for TKA - early mobilisation, less fall risk."},
  {id:"popliteal",name:"Popliteal Sciatic",region:"Below-knee / Foot",icon:"🦶",depth:"2-5 cm",vol:"20-30 mL",agent:"Ropivacaine 0.375-0.5%",landmark:"Popliteal crease between biceps femoris and semimembranosus",us:"Sciatic bifurcates 5-7 cm above crease",indication:"Ankle and foot surgery, BK amputations",risk:"Vascular injury, neurotoxicity",mechanism:"Blocks tibial + common peroneal (below-knee, spares medial ankle)",extra:"Inject above bifurcation. Nerve = hyperechoic 'snowflake sign'."},
  {id:"tap",name:"TAP Block",region:"Abdominal wall T7-L1",icon:"🫃",depth:"2-4 cm",vol:"20-30 mL each side",agent:"Ropivacaine 0.25-0.375%",landmark:"Triangle of Petit",us:"Between internal oblique and transversus abdominis",indication:"Laparotomy, hernia, C-section, appendicectomy",risk:"Peritoneal puncture, liver/spleen injury, intravascular",mechanism:"Blocks thoracoabdominal nerves T7-L1 in fascial plane",extra:"Subcostal TAP for supra-umbilical. Bilateral for midline. Rectus sheath for umbilical."},
  {id:"esp",name:"ESP Block",region:"Thoracic / Lumbar",icon:"🦴",depth:"3-7 cm",vol:"20-30 mL per level",agent:"Ropivacaine 0.25-0.375%",landmark:"Tip of transverse process",us:"Deep to erector spinae, superficial to transverse process",indication:"Rib fractures, thoracotomy, breast, spine, colectomy",risk:"Intravascular, pneumothorax (thoracic), dural puncture (rare)",mechanism:"Spreads in fascial plane - multilevel dorsal + ventral rami",extra:"Easy technique, low complication rate. Evidence growing vs paravertebral."},
  {id:"pecs",name:"PECS I & II",region:"Anterior chest",icon:"🩺",depth:"1-3 cm",vol:"10-15 mL each",agent:"Ropivacaine 0.25%",landmark:"Below clavicle, medial/lateral pectoral nerves",us:"PECS I: between pec major and minor. PECS II: pec minor and serratus anterior.",indication:"Breast surgery, mastectomy, axillary dissection",risk:"Intravascular, pneumothorax (rare)",mechanism:"PECS I: medial/lateral pectoral. PECS II: adds intercostal branches.",extra:"Combine with serratus for complete breast analgesia."},
  {id:"scalp",name:"Scalp Block",region:"Cranium",icon:"🧠",depth:"0.5 cm",vol:"3-5 mL per nerve",agent:"Ropivacaine 0.5%",landmark:"6 nerves: supraorbital, supratrochlear, zygomaticotemporal, auriculotemporal, greater/lesser occipital",us:"Landmark-based; US for occipital nerves",indication:"Craniotomy (awake or standard), scalp surgery",risk:"Intravascular (scalp highly vascular), haematoma",mechanism:"Blocks all cutaneous branches: frontal to occipital",extra:"Reduces opioid + anaesthetic requirements for craniotomy."},
  {id:"ankle",name:"Ankle Block",region:"Foot",icon:"👟",depth:"0.5-2 cm",vol:"5 mL per nerve",agent:"Lidocaine 2% or ropivacaine 0.5%",landmark:"5 nerves: saphenous, sural, superficial/deep peroneal, tibial",us:"Each nerve at standard anatomical landmark",indication:"Foot surgery, forefoot, toe amputation",risk:"Intravascular, ischaemia (avoid adrenaline in digits)",mechanism:"Terminal branches of sciatic and femoral nerve",extra:"5-nerve block = complete foot anaesthesia. Avoid adrenaline at ankle."},
];

export type Crisis = { title: string; col: string; trigger: string; drugs: string; signs?: string; steps: string[] };

export const CRISES: Record<string, Crisis> = {
  mh:{title:"Malignant Hyperthermia",col:T.red,trigger:"Volatile agents (sevoflurane, desflurane, isoflurane, halothane) + Succinylcholine in susceptible individuals (RYR1, CACNA1S mutations)",drugs:"DANTROLENE 2.5 mg/kg IV stat - repeat q5 min until ETCO2 normalises. Max 30 mg/kg. Each 20mg vial: reconstitute in 60mL warm sterile water.",signs:"Early: increased ETCO2, tachycardia, SpO2 decreased, rigidity. Late: hyperthermia, hyperkalaemia, myoglobinuria, DIC.",steps:["CALL FOR HELP - activate MH protocol, contact nearest MH centre","STOP all volatile agents immediately - flush machine with 10 L/min O2","Switch to TIVA (propofol) - remove patient from contaminated machine if possible","Hyperventilate 3x minute volume with 100% O2 (blow off CO2)","Dantrolene 2.5 mg/kg IV bolus - repeat q5 min until ETCO2 and HR normalise (max 30 mg/kg)","Active cooling: ice packs (axilla, groin, neck), cold IV fluids (4 degreesC), bladder lavage, surface cooling","2x large bore IV access. Arterial line for ABGs. Urinary catheter.","Treat hyperkalaemia: CaCl2 10 mg/kg IV, NaHCO3 1-2 mEq/kg, insulin 10U + 50mL 50% dextrose","Treat arrhythmias: amiodarone preferred. AVOID calcium channel blockers (lethal with dantrolene).","Metabolic acidosis: NaHCO3 if pH <7.1 with adequate ventilation","Fluid resuscitation: maintain UO >2 mL/kg/h (myoglobin renal protection)","Bloods: CK q6h, LFTs, renal function, coagulation, glucose, lactate","ICU: dantrolene 1 mg/kg q6h for 24-48h. Monitor for recurrence (up to 24h).","Family notification + arrange post-MH follow-up: specialist centre, genetic testing, IVCT/CHCT"]},
  anaphylaxis:{title:"Anaphylaxis",col:T.amber,trigger:"NMBAs (rocuronium #1), antibiotics (beta-lactams), latex, chlorhexidine, colloids, IV contrast, sugammadex (rare)",drugs:"EPINEPHRINE 0.01 mg/kg IV (adults: start 0.05-0.1 mg IV, titrate). IM 0.5 mg if no IV access. This is the FIRST and most critical drug.",signs:"CVS collapse (most common intraop), urticaria, flushing, angioedema, bronchospasm, laryngeal oedema.",steps:["STOP suspected trigger immediately","CALL FOR HELP","Epinephrine: 0.01 mg/kg IV (adult: 0.05-0.1 mg). IM if no IV (0.5 mg anterolateral thigh)","100% O2 - intubate early if airway compromise (oedema may make it impossible later)","Flat with leg elevation (Trendelenburg if severe hypotension)","IV fluid: 20 mL/kg crystalloid fast (Ringer's or NaCl 0.9%)","Epinephrine infusion if refractory: 0.01-0.1 mcg/kg/min","Secondary drugs (do NOT delay epinephrine for these):","  Chlorphenamine 10 mg slow IV (H1 antihistamine)","  Hydrocortisone 200 mg IV (onset 4-6h - not acute rescue)","  Ranitidine 50 mg IV (H2 - adjunct only)","Bronchospasm: salbutamol 4-8 MDI puffs or 5-10 mg nebulised","Refractory: vasopressin 40 IU IV, ECMO if cardiac arrest","Tryptase: serum at 0h, 1-2h, 24h (all three needed for diagnosis)","Post-event: allergy clinic referral (skin testing 4-6 weeks). MedicAlert advice. Document."]},
  last:{title:"LAST - LA Systemic Toxicity",col:T.pink,trigger:"Intravascular injection, absorption from vascular tissue, overdose. Bupivacaine > ropivacaine > lidocaine in CVS toxicity.",drugs:"INTRALIPID 20%: 1.5 mL/kg bolus over 1 min, then 0.25 mL/kg/min infusion. Max 12 mL/kg in first 30 min.",signs:"CNS first: perioral tingling, tinnitus, agitation, seizures -> coma. CVS: arrhythmia, hypotension, VF, cardiac arrest.",steps:["STOP LA injection immediately","CALL FOR HELP - declare LAST, get Intralipid 20%","100% O2, BVM ventilation, intubate if needed (hypoxia worsens toxicity)","Seizures: Midazolam 2-5 mg IV or propofol 0.5-1 mg/kg (small doses - NOT Intralipid substitute)","CARDIAC ARREST: Start CPR immediately","Intralipid 20%: 1.5 mL/kg (~105 mL for 70kg) IV bolus over 60 sec","Intralipid infusion: 0.25 mL/kg/min","If arrest continues: repeat bolus x2, double infusion to 0.5 mL/kg/min","Maximum: 12 mL/kg in first 30 min","Amiodarone for arrhythmias. AVOID lidocaine, beta-blockers, calcium channel blockers","Avoid high-dose epinephrine (>1 mcg/kg - may worsen outcome in LAST)","Alert nearest ECMO centre early if refractory arrest","Continue resuscitation longer than usual (lipid redistribution takes time)","Post-event: Yellow Card (UK), inform patient, document thoroughly"]},
  cpr:{title:"Perioperative Cardiac Arrest",col:T.green,trigger:"Haemorrhage (most common), vagal, hypoxia, tension PTX, PE, LAST, anaphylaxis, hyperK, drug error, coronary event.",drugs:"Epinephrine 1 mg IV q3-5 min | Amiodarone 300 mg after 3rd shock | CaCl2 / NaHCO3 if hyperK/acidosis",signs:"Absent pulse, asystole/VF/PEA on monitor, loss of ETCO2 waveform.",steps:["DECLARE: 'This is a cardiac arrest'. Assign roles immediately.","Start CPR: 100-120/min, 5-6 cm depth, full recoil, minimise interruptions","Remove drapes. Expose sternum. External compressions on sternum.","Ventilate: 100% O2, 10 breaths/min via ETT (or BVM)","Assign: Team leader, 2x compressors (switch q2 min), airway, drugs, defibrillator","DEFIBRILLATION (if VF/pVT): Charge 200J biphasic - clear - shock - immediately resume CPR","Repeat shock q2 min. After 3rd shock: Amiodarone 300 mg IV","Epinephrine 1 mg IV after 2nd shock (VF/pVT) or immediately (asystole/PEA)","Continue epinephrine 1 mg q3-5 min throughout","TREAT REVERSIBLE CAUSES - 4H + 4T:","  4H: Hypoxia, Hypovolaemia, Hypothermia, Hypo/Hyperkalaemia/Metabolic","  4T: Tension PTX, Tamponade, Toxins (LAST/opioid), Thrombosis (PE/MI)","HyperK: CaCl2 10 mg/kg + NaHCO3 50 mL 8.4% + insulin/dextrose + salbutamol","Open cardiac massage: if chest open, or refractory closed chest arrest","Post-ROSC: MAP >=65, SpO2 94-98%, ETCO2 35-45, temp 36-37 degreesC, glucose 6-10 mmol/L","ICU: 12-lead ECG, echo, angiography if STEMI. Debrief team. Family communication."]},
  highspinal:{title:"High / Total Spinal",col:T.purple,trigger:"Excessive LA volume/concentration for spinal, unintentional dural puncture during epidural, paravertebral or retrobulbar block.",drugs:"Epinephrine 10-50 mcg IV boluses. If arrest: 1 mg IV. Atropine 0.6-1.2 mg IV for bradycardia.",signs:"Ascending sensory block (>T4 -> arms), motor block, hypotension, bradycardia, dyspnoea, apnoea, loss of consciousness.",steps:["CALL FOR HELP immediately","100% O2 via facemask. Prepare to intubate.","Respiratory failure: RSI and intubate (cricoid - aspiration risk)","Hypotension: phenylephrine 100-200 mcg IV boluses OR epinephrine 10-50 mcg IV if bradycardic","Bradycardia: atropine 0.6-1.2 mg IV. If HR <30 or pulseless: epinephrine 1 mg + CPR","IV fluid: 500 mL crystalloid rapidly","Reassure conscious patient - they will be terrified. Explain what is happening.","Block will recede over 1-3 hours. Maintain support until recovery.","Document: LA drug, volume, level, time of onset, treatment, outcome","Debrief team and patient/family post-recovery"]},
  msfailure:{title:"Equipment Failure",col:T.amber,trigger:"ETT disconnect, circuit leak, ventilator malfunction, O2 supply failure.",drugs:"O2 cylinder + self-inflating bag (Ambu). Have backup machine available.",signs:"SpO2 decreased, loss of ETCO2, airway pressure alarm (high or low), no chest movement.",steps:["Disconnect patient from circuit immediately","Ventilate with self-inflating bag (Ambu) + O2 cylinder","Call for help + additional anaesthesia equipment","Check: ETT connection, circuit integrity (leaks), ETT position","Check O2 pipeline + cylinder pressure","Diagnose: machine, circuit, or airway problem?","Ventilator fault: hand-bag until resolved or machine replaced","O2 failure: use cylinder O2, inform surgeon of urgency","Maintain anaesthesia: switch to TIVA if volatile unavailable","Document and report formally (critical incident, MHRA if device fault)"]},
};

export const VASOPRESSORS = [
  {name:"Norepinephrine",dose:"0.01-2 mcg/kg/min",moa:"alpha1>beta1",use:"1st line: septic shock",note:"Central line preferred"},
  {name:"Vasopressin",dose:"0.01-0.04 U/min (fixed)",moa:"V1R",use:"Add-on to NE in refractory shock",note:"Non-catecholamine, not titrated"},
  {name:"Epinephrine",dose:"0.01-1 mcg/kg/min",moa:"alpha+beta1+beta2",use:"Anaphylaxis, cardiac arrest, low CO",note:"Low dose = beta dominant"},
  {name:"Phenylephrine",dose:"0.5-5 mcg/kg/min or 50-200 mcg bolus",moa:"alpha1 only",use:"Spinal hypotension, SVT+hypotension",note:"No inotropy. Safe in obstetrics."},
  {name:"Dopamine",dose:"2-20 mcg/kg/min",moa:"DA>beta>alpha dose-dependent",use:"Alternative (higher arrhythmia risk)",note:"Avoid in septic shock (SOAP II)"},
  {name:"Dobutamine",dose:"2-20 mcg/kg/min",moa:"beta1>beta2",use:"Cardiogenic shock, low CO",note:"increased CO, decreased SVR. May drop BP."},
  {name:"Milrinone",dose:"50-75 mcg/kg load then 0.375-0.75 mcg/kg/min",moa:"PDE3 inhibitor",use:"Post-cardiac surgery low CO, RV failure",note:"Inodilatation. Reduce in renal failure."},
  {name:"Terlipressin",dose:"1-2 mg IV q6h",moa:"V1R (long-acting)",use:"Hepatorenal syndrome, variceal bleeding",note:"Long-acting vasopressin prodrug"},
];

export type AirwayNode = {
  q: string;
  type?: "action" | "danger";
  yes?: string;
  no?: string;
  next?: string | null;
  items?: string[];
};

export const AIRWAY_TREE: Record<string, AirwayNode> = {
  start:{q:"Is this an ANTICIPATED difficult airway?",yes:"anticipated",no:"unanticipated"},
  anticipated:{q:"Is the patient cooperative and oxygenation adequate for an awake technique?",yes:"awake",no:"ga_backup"},
  awake:{q:"Awake intubation technique selected.",type:"action",next:"success",items:["Awake FOI (gold standard for predicted difficult airway)","Awake video laryngoscopy (faster than FOI)","Awake tracheotomy if pharyngeal/supraglottic pathology","Topicalise airway (SAYG/nerve blocks). Cooperative sedation (dex/remi TCI).","Surgical airway team and equipment on standby"]},
  ga_backup:{q:"Cannot cooperate for awake technique. Proceed with GA + expert backup + surgical airway standby.",type:"action",next:"unanticipated",items:["Expert anaesthetist mandatory","Video laryngoscope as primary device","Tracheotomy/cricothyrotomy set open and ready","Surgeon scrubbed if very high risk"]},
  unanticipated:{q:"Unexpected difficult airway after induction. Was first intubation attempt successful?",yes:"success",no:"failed"},
  success:{q:"✅ Intubation successful.",type:"action",next:null,items:["Sustained ETCO2 waveform (gold standard)","Bilateral breath sounds - 5-point auscultation","SpO2 rising. ETT depth confirmed and secured.","Consider CXR if uncertainty"]},
  failed:{q:"Failed first attempt. Can you maintain mask ventilation (SpO2 >=90%)?",yes:"nonemergency",no:"cico"},
  nonemergency:{q:"Ventilation maintained - NOT yet an emergency.",type:"action",next:"attempt2",items:["CALL FOR HELP immediately","Oxygenate between all attempts","Max 3 attempts total (+1 by most experienced clinician)","Reposition: ear-to-sternal notch, BURP, smaller ETT","Switch device: DL -> video laryngoscope, use bougie"]},
  attempt2:{q:"Was second intubation attempt successful?",yes:"success",no:"sga"},
  sga:{q:"Insert supraglottic airway (LMA, i-gel, intubating LMA)",type:"action",yes:"sga_ok",no:"cico",items:["Appropriate size. Lubricate well.","Insert carefully, attach ETCO2","Intubating SGA: allows FOI/bougie through device"]},
  sga_ok:{q:"SGA in place. SpO2 >=94%?",yes:"sga_plan",no:"cico"},
  sga_plan:{q:"SGA oxygenating. Decide next step with team.",type:"action",next:null,items:["Option 1: Wake patient -> awake intubation plan","Option 2: Intubate through SGA (FOI or bougie)","Option 3: Proceed if surgery appropriate and SGA adequate","Option 4: Surgical tracheotomy under SGA oxygenation"]},
  cico:{q:"⚠️ CICO: CANNOT INTUBATE - CANNOT OXYGENATE. SpO2 falling. EMERGENCY.",type:"danger",yes:"efona",no:"efona"},
  efona:{q:"🚨 IMMEDIATE eFONA - DO NOT DELAY. Declare CICO aloud.",type:"danger",next:null,items:["DECLARE: 'CICO - front-of-neck access NOW'","Extend neck fully. Identify cricothyroid membrane (CTM).","Scalpel-Finger-Bougie (DAS eFONA technique):","  1. Horizontal stab incision through CTM","  2. Hook index finger through incision (cranially)","  3. Insert bougie caudally through CTM","  4. Railroad 6.0 cuffed ETT over bougie","  5. Inflate cuff, confirm ventilation via ETCO2","Surgical tracheotomy if ENT/MF surgeon scrubbed","100% O2 push via SGA during eFONA attempt","Document: time of CICO declaration, technique, time to oxygenation"]},
};
