import { T } from "./theme";

export type Phase = { phase: string; items: string[] };
export type Procedure = {
  id: string; name: string; icon: string; color: string; category: string; steps: Phase[];
};

export const PROCEDURES: Procedure[] = [
  {id:"ga",name:"GA Standard Induction",icon:"💉",color:T.accent,category:"General",steps:[
    {phase:"Pre-Induction",items:["Confirm identity, consent signed, allergies (drug/latex/food)","Airway assessment: Mallampati, mouth opening, thyromental distance, neck mobility, dentition","Fasting: solids >=6h, clear fluids >=2h","IV access - patent, adequate gauge","Pre-oxygenate: 3 min 100% O2 (tight mask seal) or 8 vital capacity breaths","Monitoring: SpO2, ECG, NIBP q2-3 min","Machine check: O2, agent, flows, circuit, APL valve, suction","Intubation kit: laryngoscope light, ETT sizes +/-1, stylet, 10mL syringe, fixation tape","Drugs drawn up and labelled: induction agent, opioid, NMBA, vasopressor","Ramped position if obese/obstetric. Call anaesthetic assistant."]},
    {phase:"Induction",items:["Pre-induction opioid if planned (fentanyl 1-3 mcg/kg)","Propofol 1-2.5 mg/kg - titrate to loss of verbal contact","Loss of consciousness confirmed - proceed to airway management","NMBA if intubating - wait for TOF to confirm relaxation","Jaw thrust, cricoid if RSI. Gentle mask ventilation if not RSI."]},
    {phase:"Intubation",items:["Ear-to-sternal notch alignment (sniffing/ramped position)","DL or video laryngoscopy - note C/L grade and document","ETT past cords under vision. Cuff inflated 20-30 cmH2O.","ETCO2 - confirm sustained waveform (gold standard)","5-point auscultation: bilateral axillae, anterior chest, epigastrium","Secure ETT: F 21cm, M 23cm at teeth. Document depth.","Ventilator: TV 6-8 mL/kg IBW, PEEP 5, RR -> EtCO2 35-40, FiO2 0.4","Commence maintenance volatile/TIVA. BIS/entropy if available."]},
    {phase:"WHO Surgical Safety Time Out",items:["Patient identity, site, procedure, side (if applicable)","Surgeon, anaesthetist, nurse all introduce by name and role","Antibiotic prophylaxis given within 60 min of incision","DVT prophylaxis confirmed (TEDS, compression device, LMWH)","Allergies re-confirmed with team","Surgeon: critical steps, expected blood loss, special equipment","Anaesthetist: patient-specific concerns shared","Nurse: sterility confirmed, equipment counted and available"]},
  ]},
  {id:"rsi",name:"RSI - Rapid Sequence Induction",icon:"⚡",color:T.red,category:"General",steps:[
    {phase:"Preparation",items:["INDICATION confirmed: full stomach, GORD, bowel obstruction, trauma, pregnancy, obesity, inadequate fasting","Discuss plan + backup plan + CICO rescue plan with team","Position: ramped (obese) or sniffing. Head up 20 degrees if possible.","Two suction devices - Yankauer immediately available","Pre-oxygenate: 3+ min 100% O2 (target EtO2 >87%). HFNO 15 L/min during apnoea if available.","Drugs: induction agent + suxamethonium 1.5 mg/kg OR rocuronium 1.2 mg/kg","Video laryngoscope prepared and tested as primary or backup","Plan communicated: 'RSI - no positive pressure until tube confirmed'","Cricoid pressure briefed with assistant"]},
    {phase:"Drugs & Induction",items:["Fentanyl 1-2 mcg/kg IV (if haemodynamically stable) - 3 min before","Induction: propofol 1.5-2 mg/kg OR thiopentone 4-5 mg/kg (ICP) OR ketamine 1.5-2 mg/kg (haemodynamic instability) OR etomidate 0.3 mg/kg (cardiac risk)","Cricoid pressure applied: 10N awake -> 30N after LOC","Suxamethonium 1.5 mg/kg IV -> fasciculations then relaxation (~60 sec)","OR rocuronium 1.2 mg/kg IV (onset 60 sec) - have sugammadex 16 mg/kg immediately available","NO ventilation between induction and intubation (unless SpO2 <90%)"]},
    {phase:"Intubation & Confirmation",items:["Intubate at 60 sec (sux) or 60-90 sec (roc 1.2 mg/kg)","DL or video laryngoscopy","ETCO2 waveform confirmation - immediate and sustained","Cuff inflated before first ventilation","5-point auscultation","Release cricoid ONLY after ETT position confirmed","Failed attempt: call for help, do NOT persist >3 attempts total","Reoxygenate between attempts - target SpO2 >94%","Rescue SGA if can ventilate but cannot intubate","CICO: declare early, eFONA (scalpel-finger-bougie)"]},
    {phase:"Post-Intubation",items:["Secure ETT, note depth at teeth","Bilateral breath sounds, EtCO2 waveform, SpO2 rising","Set ventilator: TV, PEEP, RR, FiO2","Document: laryngoscopy grade, blade, attempt number, adjuncts","Notify surgeon - proceed when safe","Plan extubation strategy (RSI does NOT mandate awake extubation)"]},
  ]},
  {id:"spinal",name:"Spinal Anaesthesia",icon:"🫀",color:T.green,category:"Regional",steps:[
    {phase:"Pre-Procedure",items:["Contraindications: coagulopathy (INR>1.5, plt<80, LMWH<12h), site infection, patient refusal, raised ICP","Anticoagulant check per ASRA guidelines","Consent: hypotension, PDPH 0.5-2%, nerve injury (rare), meningitis (rare)","IV access (large bore). Pre-load 500 mL crystalloid or vasopressor ready.","Equipment: pencil-point needle 25-27G, sterile kit, isobaric vs hyperbaric LA","Monitoring: SpO2, ECG, NIBP q2-3 min. Level testing (cold spray).","Position: sitting (L3/4 or L4/5) or lateral decubitus","Vasopressor ready: phenylephrine 100 mcg boluses or infusion 50-100 mcg/min"]},
    {phase:"Procedure",items:["Sterile field, scrub, gloves. Mark intended level.","Draw up: bupivacaine 0.5% heavy 2-3 mL +/- fentanyl 10-25 mcg +/- morphine 100-200 mcg","Identify midline and interspace (L3/4 or L4/5 - below conus at L2)","Skin LA: lidocaine 1% 1-2 mL for introducer","Introduce 22G introducer -> advance 25-27G pencil-point spinal needle","Advance through ligaments. Characteristic LOR through dura.","Remove stylet: clear CSF confirms intrathecal position - ESSENTIAL","Aspirate 0.2 mL CSF, inject LA slowly, aspirate again mid-injection","Remove needle, apply pressure","Document: volume, agent, level, position, attempts"]},
    {phase:"Post-Procedure",items:["Position patient (hyperbaric: adjust table for target level)","Test block at 5 min: cold spray at each dermatome","Target level: T10 (perineum), T6 (laparotomy), T4 (Caesarean)","BP every 2-3 min for 20 min","Hypotension (SBP <90 or >20% fall): phenylephrine 50-100 mcg IV. Bradycardia: ephedrine 6-9 mg. Severe: atropine/epinephrine.","Bradycardia: atropine 0.6 mg IV if HR <50","High spinal (>T4): O2, vasopressor, leg elevation, prepare to intubate","Total spinal: RSI, vasopressors, reassure patient","Document: final block level, complications, vasopressor requirements"]},
  ]},
  {id:"epidural",name:"Epidural Insertion",icon:"🔵",color:T.purple,category:"Regional",steps:[
    {phase:"Pre-Procedure",items:["Indications: labour analgesia, major surgery, chronic pain","Contraindications: coagulopathy, bacteraemia, patient refusal, site infection","ASRA anticoagulant check: LMWH prophylaxis 12h, therapeutic 24h; warfarin INR<1.5; clopidogrel 7 days","Consent: PDPH 1%, nerve injury, infection, haematoma, failed/partial block","IV access, monitoring, resuscitation equipment ready","Position: lateral decubitus or sitting - maximal spine flexion ('shrimp')","Equipment: Tuohy 16-18G, LOR syringe, catheter, filter, fixation, test dose LA"]},
    {phase:"Procedure",items:["Sterile field, scrub, gloves. Mark level.","Skin LA at chosen interspace (L1/2-L4/5; T4-T12 thoracic)","Tuohy needle midline (or paramedian approach)","Advance: supraspinous -> interspinous -> ligamentum flavum (resistance increases)","LOR syringe (saline preferred) - constant pressure advancing","Sudden LOR = epidural space (typically 4-5 cm deep)","Test LOR: 0.5-1 mL saline freely - confirms position","Thread catheter 3-5 cm into space. Remove Tuohy while securing catheter.","Aspirate: no blood (intravascular), no CSF (intrathecal)","Test dose: lidocaine 2% 3 mL + epinephrine 15 mcg","Positive: tachycardia >20 bpm (IV) or dense motor block <5 min (IT)","Fix catheter. Attach filter. Label clearly: 'EPIDURAL - NOT FOR IV USE'"]},
    {phase:"Management",items:["Loading: ropivacaine 0.1-0.25% 10-20 mL in 5 mL divided doses","Maintenance: PCEA ropivacaine 0.1% + fentanyl 2 mcg/mL (5-10 mL/h background, 5 mL PCEA bolus, 20 min lockout)","Test sensory level q15 min for 1h. Document dermatomal level.","Labour target: T10. Inadequate/one-sided: troubleshoot position, top-up, or re-site.","Surgical top-up: lidocaine 2% (fast) or ropivacaine 0.75% (dense)","PDPH if wet tap: conservative (bed rest, hydration, caffeine). Blood patch 15-20 mL if >24h."]},
  ]},
  {id:"awake_foi",name:"Awake Fibreoptic Intubation",icon:"🔦",color:T.amber,category:"Airway",steps:[
    {phase:"Preparation",items:["Indications: predicted difficult airway, limited mouth opening, unstable C-spine, airway tumour, morbid obesity (STOP-BANG >=5)","Patient communication and consent - gain trust and cooperation","IV access, SpO2, NIBP, ECG. Supplemental nasal O2 throughout.","Antisialogogue: glycopyrrolate 0.2 mg IV/IM 20 min before","Sedation: midazolam 0.5-1 mg + dexmedetomidine 0.5 mcg/kg over 10 min, OR remifentanil TCI 1-3 ng/mL","Scope: adult 3.8-5mm, checked, anti-fog solution, working light source","ETT loaded on scope (>5.5mm oral, >6.5mm nasal). Flexible tip lubricated.","Video laryngoscope and surgical airway as backup. Suction ready."]},
    {phase:"Topicalisation",items:["Target: 4-9 mg/kg total lidocaine to airway mucosa","Nasal route: 10% cocaine paste (vasoconstriction + anaesthesia) OR xylometazoline + lidocaine 4%","Oral route: atomised lidocaine 4% to oropharynx, tongue base, tonsillar pillars","Superior laryngeal nerve block: 2 mL lidocaine 2% each side (below greater cornu of thyroid)","Trans-tracheal block: 23G through cricothyroid membrane, aspirate air, inject 3 mL lidocaine 4%, patient coughs","Spray-as-you-go (SAYG): lidocaine 1-2 mL aliquots via scope working channel at each level","Allow 3-5 min per level before advancing. Patient should tolerate scope without coughing."]},
    {phase:"Intubation",items:["Load ETT onto scope. Ovassapian/Berman airway or tongue traction for oral route.","Advance scope midline: epiglottis -> arytenoids -> vocal cords","SAYG lidocaine to cords. Patient takes deep breath.","Advance scope through cords in inspiration. Visualise carina.","Confirm at carina (scope not past main stem orifice)","Advance ETT over scope (rotate anti-clockwise if held up)","Confirm ETT at cords and carina via scope","Withdraw scope while holding ETT firmly","INDUCE ANAESTHESIA NOW with chosen agent","Inflate cuff, confirm ETCO2, secure ETT. Document."]},
  ]},
  {id:"arterial",name:"Arterial Line Insertion",icon:"📍",color:T.pink,category:"Monitoring",steps:[
    {phase:"Preparation",items:["Sites: radial (1st choice), femoral, brachial, dorsalis pedis, ulnar","Equipment: 20G arterial cannula, transducer set, flush (heparinised saline or NS), pressure bag, cable","Zero: transducer at mid-axillary line, 4th intercostal space (right atrium level)","Wrist dorsiflexed 45-60 degrees over roll, taped securely","Skin prep: chlorhexidine. Sterile gloves. Fenestrated drape.","LA: lidocaine 1% 0.5-1 mL intradermal (avoid deep - can obscure pulse)"]},
    {phase:"Insertion",items:["Palpate radial pulse clearly","Transfixion: advance 30-45 degrees, withdraw stylet, slowly withdraw until flashback, advance cannula","OR Seldinger: needle into artery, thread 0.021 wire, nick skin, dilate, advance cannula","Confirm arterial: pulsatile blood on aspiration","Connect transducer, flush, and zero","Arterial waveform: sharp upstroke, dicrotic notch","Secure cannula (suture or adhesive). Label: 'ARTERIAL - DO NOT INJECT'"]},
    {phase:"Troubleshooting",items:["Damped waveform: air bubbles, kinking, thrombus, vasoconstriction","Flush carefully (not forcefully if clot suspected)","Check all connections and transducer level","Haematoma: firm pressure. Large: resite, check perfusion.","Vasospasm: warm extremity, phentolamine locally","Ischaemic distal digit: remove cannula, warm, anticoagulate if persisting"]},
  ]},
  {id:"cvc",name:"Central Venous Line (CVC)",icon:"🔗",color:T.green,category:"Monitoring",steps:[
    {phase:"Preparation",items:["Indications: vasopressors, CVP monitoring, multi-lumen access, failed peripheral, TPN, pacing","Sites: right IJV (preferred), subclavian, femoral (highest infection risk)","Contraindications: coagulopathy (relative), ipsilateral pneumothorax, local infection","Full aseptic technique: cap, mask, sterile gown, sterile gloves, full sterile drape","Ultrasound mandatory (NICE guidelines): confirm patency, real-time needle entry","Positioning: Trendelenburg (IJV/subclavian - engorges vein, reduces air embolism risk)","Equipment: CVC kit, 3-way stopcock, flushed lines, suture, dressing"]},
    {phase:"Insertion - Right IJV",items:["US: identify IJV (compressible, lateral to carotid), confirm patency","Needle at 45 degrees toward ipsilateral nipple. In-plane US guidance preferred.","Aspirate freely - dark, non-pulsatile venous blood confirms position","If pulsatile/arterial: remove needle, firm pressure 5+ min","Thread J-wire - advance without resistance. Warn: palpitations if wire in RV.","Nick skin, dilate over wire (single pass)","Thread catheter over wire - hold wire at all times, remove after catheter seated","Aspirate all lumens (confirm blood), flush, cap unused lumens","Suture, sterile dressing","Post-procedure CXR: tip at cavoatrial junction, exclude pneumothorax"]},
    {phase:"Post-Insertion",items:["CXR: tip at T5/6 (right lateral border of SVC/cavoatrial junction)","Pneumothorax: compare bilateral lung markings","Label each lumen clearly (distal = largest and most versatile)","Document: site, operator, attempt number, gauge/length, confirmation","Complications: pneumothorax, arterial puncture, air embolism, arrhythmia, haematoma","Air embolism: Durant's manoeuvre (left lateral, head down), aspirate via CVC, 100% O2"]},
  ]},
  {id:"extubation",name:"Extubation Protocol",icon:"🫁",color:T.green,category:"General",steps:[
    {phase:"Pre-Extubation Assessment",items:["Surgical: procedure complete, haemostasis achieved, no airway oedema","Airway: was intubation easy? Difficult -> consider awake extubation","Cuff leak test: deflate cuff - audible leak? Absent = laryngeal oedema -> dexamethasone 8 mg IV, wait 1h","Respiratory: TV >6 mL/kg, RR 10-20, PEEP <=5 cmH2O, adequate spontaneous effort","Neuromuscular: TOF ratio >=0.9. Clinical: 5 sec head lift, grip strength, tongue protrusion.","Patient: awake, following commands, protecting airway","Temperature: core >36 degreesC (normothermic)","Pain: controlled - not over-sedated, not in agony","Haemodynamics: stable, vasopressors off/weaning","Reversal: neostigmine + glyco given, or sugammadex if rocuronium/vecuronium"]},
    {phase:"Extubation",items:["Head up 30-45 degrees (reduces aspiration risk, improves FRC)","Pre-oxygenate: 100% O2 3-5 min","Suction oropharynx under direct vision (blood, secretions)","Suction ETT lumen if secretions present","Deflate ETT cuff fully","Remove securing tape/device","Remove tube on positive pressure (cough clears secretions) OR during expiration (less laryngospasm)","Immediate face mask 100% O2 for 2-3 min","Assess: SpO2, RR, airway patency, phonation (hoarseness = laryngeal oedema)","Keep laryngoscope and re-intubation equipment immediately available x15 min"]},
    {phase:"Post-Extubation",items:["O2 supplement during transport and in recovery","SpO2 monitoring minimum 30 min in recovery room","Stridor/hoarseness: nebulised adrenaline 5 mg (1:1000, 5 mL)","Laryngospasm: 100% O2 + jaw thrust/CPAP -> propofol 0.5 mg/kg -> suxamethonium 0.5-1 mg/kg (total)","PONV management, pain assessment, temperature check","Difficult intubation: consider airway exchange catheter (AEC) left in place 30-60 min","AEC: allows re-intubation or jet oxygenation if needed","Document: extubation time, any complications, post-extubation assessment"]},
  ]},
  {id:"lma",name:"LMA / Supraglottic Airway",icon:"🔵",color:T.accent,category:"Airway",steps:[
    {phase:"Preparation",items:["Indications: elective surgery (NOT full stomach), short procedures, airway rescue","Contraindications (relative): full stomach/GORD, morbid obesity, prone (most SGAs), high PEEP needed","Device selection: Classic LMA, ProSeal (2nd gen, high seal), i-gel (no cuff), LMA Supreme, AuraGain (can intubate)","Size: 1 (<5kg), 1.5 (5-10kg), 2 (10-20kg), 2.5 (20-30kg), 3 (30-50kg), 4 (50-70kg), 5 (70-100kg)","Lubricate posterior surface. Deflate cuff (classic) or per manufacturer.","Adequate depth of anaesthesia before insertion (jaw relaxed)"]},
    {phase:"Insertion",items:["Sniffing position (neutral or slight extension)","Open mouth with non-dominant hand. Hold LMA like pen.","Index finger guides posterior surface over tongue pressing on hard palate","Advance in curved motion along pharynx until resistance at hypopharynx","Inflate cuff per recommended volume (do not over-inflate)","Attach circuit: bilateral chest rise, ETCO2 waveform, airway pressure <20 cmH2O (1st gen) / <25 cmH2O (2nd gen)","Auscultate bilaterally. No audible leak at normal tidal volume.","Secure device, note depth at teeth. Document size and cuff volume.","Poor seal: adjust position, re-inflate, consider jaw thrust"]},
    {phase:"Intraoperative Management",items:["Adequate anaesthesia depth - no cough or bucking with SGA in situ","Peak airway pressure alarm <=25 cmH2O","Use 2nd gen device if IPPV required (ProSeal/i-gel/Supreme)","Gastric tube via drain channel if 2nd gen device","Monitor ETCO2 waveform continuously","Patient supine/semi-recumbent (avoid head-down unless 2nd gen)","Removal: awake/following commands (preferred) or deep (avoids laryngospasm)"]},
  ]},
  {id:"tiva",name:"TIVA - Total IV Anaesthesia",icon:"💧",color:T.purple,category:"General",steps:[
    {phase:"Setup & Planning",items:["Indications: avoid volatiles (PONV risk, MH susceptibility, ENT laser, neurosurgery)","TCI models: Marsh or Schnider (propofol); Minto (remifentanil)","Equipment: dedicated TIVA pump, anti-siphon valves, 1-way valves on all drips, TIVA set","Dedicated TIVA IV line - label clearly. No other drugs via TIVA line.","Anti-reflux valve mandatory (prevents retrograde flow)","Consciousness monitoring: BIS or Entropy (target BIS 40-60)","AWARENESS RISK: pump alarm, IV disconnection, infiltration. Check q15 min.","Pre-calculate and preset TCI targets before induction"]},
    {phase:"Induction",items:["Propofol TCI: Ce 4-8 mcg/mL (Schnider) or Cp 4-6 mcg/mL (Marsh)","Remifentanil TCI: Ce 3-8 ng/mL for induction (Minto)","Pre-oxygenate 3 min 100% O2","Commence propofol TCI. Loss of consciousness at Ce ~3-4 mcg/mL.","Smooth induction. Give NMBA once unconscious.","Manual TIVA alternative: propofol bolus + remifentanil infusion"]},
    {phase:"Maintenance",items:["Propofol: Ce 2.5-4 mcg/mL (titrate to BIS 40-60)","Remifentanil: Ce 1-4 ng/mL (titrate to haemodynamics and surgical stimulation)","Manual propofol: 4-10 mg/kg/h (reduce to 4-6 after 30 min)","Check IV site and infusion every 15 min (awareness risk if disconnect)","Document pump settings q30 min","PONV prophylaxis: dexamethasone 4-8 mg at induction + ondansetron 4 mg at end","Muscle relaxation managed separately with TOF monitoring"]},
    {phase:"Emergence",items:["Stop remifentanil 2-5 min before end (no residual - rapid offset)","Reduce propofol to Ce 2-3 mcg/mL near end of surgery","Post-op analgesia: morphine/oxycodone/paracetamol/NSAIDs early (remifentanil = NO post-op analgesia)","Patient responsive at Ce ~1-1.5 mcg/mL","Extubate per extubation protocol. Usually rapid recovery.","Document: total propofol mg/kg, remifentanil volume, BIS values"]},
  ]},
];
